### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by xytsrj** [fffonion/JJGet#1]
hello！用户名支持邮箱吗？我用邮箱登录失败QAQ

**Comment by fffonion** [comment]
登录部分年久失修，现在暂时登录不了惹

**Comment by xytsrj** [comment]
> 登录部分年久失修，现在暂时登录不了惹

等您啊太太！（是的微博也是我）

**Comment by fffonion** [comment]
修好了（大概），试试新版？http://pan.baidu.com/s/1EikSA

**Comment by xytsrj** [comment]
> 修好了（大概），试试新版？http://pan.baidu.com/s/1EikSA

登录解决了！谢谢太太！！！！（抱着您三百六十度旋转）
但是发现一个bug VIP章下载后会有代码每章最开头
代码如下：

　　<script>
                                    function getSnapshot() {
                                        var snapid = $("[name='snapshotList']").val();
                                        var href;
                                        if (snapid==0) {
                                            href = "http://my.jjwxc.net/onebook_vip.php?novelid=3886659&chapterid=65";
                                        } else {
                                            href = "http://my.jjwxc.net/onebook_vip.php?novelid=3886659&chapterid=65"+'&snapid='+snapid;
                                        }
                                        window.location.href = href;
                                    }
                                </script>

**Comment by xytsrj** [comment]
> 修好了（大概），试试新版？http://pan.baidu.com/s/1EikSA

顺便 我突然发现用的例图是镇魂（我又快乐了ww

**Comment by fffonion** [comment]
script的问题修好了

对的，紧跟时代潮流www

**Comment by xytsrj** [comment]
可以正常使用了！感谢！ww
