### ISSUE TITLE
晋江防盗字体识别交流

### ISSUE THREAD

**Issue by yingziwu** [fffonion/JJGet#11]
作者您好，最近因为晋江更新字体，我之前采用的[反爬字体表](https://github.com/7325156/jjwxcNovelCrawler/tree/master/%E5%8F%8D%E7%88%AC%E8%99%AB%E5%AF%B9%E7%85%A7%E8%A1%A8)也因此失效。

为此，我自己写了一个[晋江反爬字体识别工具](https://github.com/yingziwu/jjwxcFontTables)。

今天打开之前使用的反爬字体表，发现了这个仓库。`find_by_coord` 函数通过直接比较字体文件来判断是否为同一字，这给了我很大的启发。

非常感谢。

**Comment by fffonion** [comment]
咦最近更新字体了吗 🤦

**Comment by yingziwu** [comment]
增加了许多字体，现在已经有300多个字体文件了，翻了一倍。

https://yingziwu.github.io/jjwxcFontTables/
