### ISSUE TITLE
字体解码错误

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#12]
作者大大，最近这几天使用的时侯发现有字体解码错误，目前我看到的是“想”这个字有时后会被替换成"愚"，不知道是否为晋江修改防盗字体导致

**Comment by fffonion** [comment]
嗯，这个可能有误识别，能贴一下是哪个字体吗（或者哪一个章节）？

**Comment by piedfallow** [comment]
这个我可能要看一下，因为我存的时候会自己手动更改，主要是只有这个字，而且也不是每次都会遇到，所以可能到时候再跟大大说，谢谢。
我查了一下别人的反扒字体(之前有个字体交流的问题帖)的部份，“想”这个字的编码是U+eef4，我不是很确定大大要的是不是这个，如果不是，再麻烦大大跟我说，我再看看

**Comment by piedfallow** [comment]
我看了一下其他脚本所使用的解码器好像都是https://jjwxc.bgme.bid/${fontName}.json这个，提供给大大参考

**Comment by fffonion** [comment]
嗯，印象里现在这些都用的同一套方法；不过“愚“这个字不在常用字表里，你可以用记事本打开`.jjfont`文件，然后把"愚"全部替换成"想"

**Comment by piedfallow** [comment]
好的，謝謝大大

**Comment by piedfallow** [comment]
大大不好意思，想问一下如果我找到这个字，我要如何查看他的编码呢？

**Comment by piedfallow** [comment]
好的！谢谢大大，因为怕象是"愚昧"、"愚蠢"之类的字被替换，不过我想就像大大说的不是常用字，应该不太会发生这种事

**Comment by fffonion** [comment]
嗯，不是替换下载的txt，是替换本地的匹配表缓存，是`.jjfont`这个文件；可以直接用记事本打开来替换；这样以后下载就不会匹配错了，已经下载的txt就得重新下一遍了w

**Comment by piedfallow** [comment]
了解！谢谢大大

**Comment by piedfallow** [comment]
大大，我有找到一篇关于这个问题的讨论，给您参考
https://github.com/7325156/jjwxcNovelCrawler/issues/12

**Comment by fffonion** [comment]
好的，我晚点换个OCR方案试试，目前识别错误还是因为偷懒样本太小了 😄 
app接口感觉有点不future proof，暂时不搞过去了

**Comment by piedfallow** [comment]
谢谢大大！ 😆因为刚好有看到所以分享给您！真的很感谢您的心血👍
