### ISSUE TITLE
账号无法登陆

### ISSUE THREAD

**Issue by JJYAY** [fffonion/JJGet#13]
大大，求问为什么最近账号一直登陆不了，登陆后软件一直自动关闭

**Comment by fffonion** [comment]
试试新版？

**Comment by JJYAY** [comment]
登陆还是会被弹出来，哭了，大大，我需要你！！！

**Comment by fffonion** [comment]
@JJYAY 我明天试试，好像jj网页是用滑块验证码了，软件用的图形可能裂开了

**Comment by JJYAY** [comment]
收到，感谢大大！

**Comment by JJYAY** [comment]
大大，我等你，哭了

**Comment by JJYAY** [comment]
好的！大大有空再弄就行，爱你！

**Comment by fffonion** [comment]
我试了一下好像还是可以登录的（思考
你那边点登录完成之后程序有提示 获取用户信息 什么的吗？

**Comment by JJYAY** [comment]
就是点进程序过后，输入了账号和密码，然后显示登陆失败弹出验证码后，输入验证码点击登陆，然后程序正在登陆，鼠标箭头一直转圈，过几秒自动弹出程序，没有提示（难道就我一个人这种情况！哭了，会不会和账号密码设置也有关系啊）

**Comment by JJYAY** [comment]
就是获取用户信息的时候弹出了程序！

**Comment by piedfallow** [comment]
验证码不是在输入账号密码后会直接显示吗？

**Comment by JJYAY** [comment]
那不知道为啥，好奇怪，难道我电脑有问题！凄凄惨惨

**Comment by piedfallow** [comment]
重新安装NET 3.5试看看？

**Comment by fffonion** [comment]
可以试试输入用户名之后，点一下密码框，然后等一下，那个时候应该会跳出验证码。等跳出来之后再输密码和验证码

**Comment by JJYAY** [comment]
还是不行，会被弹出了，哭了，可能就是我电脑不行，然后换了新注册的账号，那个账号密码是输对的但是一直显示密码错误

**Comment by piedfallow** [comment]
结果我也遇到同样问题了，输完账号密码后验证码不会出现，然后程式会自动关闭

**Comment by piedfallow** [comment]
刚刚看了下，感觉好像是晋江本身的问题，网页现在打不开了

**Comment by JJYAY** [comment]
好！我再多试试

**Comment by piedfallow** [comment]
大大，突然无法登入了，输入账号密码后等待验证码的时候，程序会闪退，就算跑出验证码，输入后一样会闪退，晋江网页正常，手机版也正常，不知道是何原因造成

**Comment by piedfallow** [comment]
大大，突然无法登入了，输入账号密码后等待验证码的时候，程序会闪退，就算跑出验证码，输入后一样会闪退，晋江网页正常，手机版也正常，不知道是何原因造成

**Comment by piedfallow** [comment]
这两天都无法顺利登入，会闪退，勉强登入后会出现下列情况导致无法正常下
![1](https://user-images.githubusercontent.com/88279588/179381682-ddc15b27-1d45-4b53-98ac-05cda88b162c.png)
载

**Comment by fffonion** [comment]
这个错误感觉像是jj那边炸了，挂个代理试试？

**Comment by piedfallow** [comment]
要怎么挂代理？ ？ ？ 😂我没用过

**Comment by piedfallow** [comment]
目前最主要是在输入账号后基本就闪退，有时后会勉强出现正在登入，但是仍会闪退，大约要试20次以上才可能登入一次(不论是否勾选手机版)，登入后要下载两个VIP章节会出现上面的错误(尤其是第一个章节会无法下载)，试过单独下载该章节，仍会出现上述错误，使用代理后，会出现下面情况，必须把代理关闭后才能下载，试过先把代理关闭后读取到该文章再开启，仍旧无法下载，目前晋江网页与手机版正常，没有出现开不起来的问题，会不会是上次提到的滑块问题？
![1](https://user-images.githubusercontent.com/88279588/179410890-a1067096-937c-4972-9446-531827b9b64a.png)

**Comment by fffonion** [comment]
可能是小学数学验证码用不了了，等我空了再修一下！
或者有什么别的软件可以用的话，我可以去学习一下 😄

**Comment by piedfallow** [comment]
数学跟英文+数字的都不能用😂😂😂
目前大部份好像都是从网页直接下手(不用开新软体)，我还没有遇到类似的😂😂😂
谢谢大大！等你修好 😄 😄

**Comment by laisyaoran** [comment]
我C#小白一个。也不确定我对不对，就说一下我现在好像可以解决的方法。

我也遇到了上面的问题（闪退及vip小说下载失败）。然后我下源码测试了下，
闪退是因为http请求报错，登陆流程的一个请求代码好像没有写错误回调，所以程式自己会崩溃。
（操作顺序是：先输用户名，然后点击密码输入框，登陆按钮会立马变灰不可用，然后几秒后程式就会闪退）
然后就去度娘了一下相关错误，
一个网站告诉我这是TSL协议问题，
`调用WebService是，默认使用TLS 1.1协议。如果服务器关闭了TLS1.1，使用TLS1.2时，客户端必须增加1.2的语法，否则会出现错误：`
在http请求前要加入下面的代码
`ServicePointManager.SecurityProtocol = (SecurityProtocolType)192 | (SecurityProtocolType)768 | (SecurityProtocolType)3072;`

然后我在HttpUtil.cs文件的50行，加入了上面的代码，重新打包。
然后就不闪退了，小说也能下载成功了。

然后我在自己电脑测试了几次，
未加代码的版本 就是大概率会不行，偶尔不知道为啥又行，
加了就是都行

这代码啥用我也看不懂，纯属百度，也不知道是不是真的因为这个，给大佬参考了。😂

**Comment by fffonion** [comment]
😂 感觉是JJ用的CDN的问题，可能用了多家CDN有些开了tls1.1有些没开，怪不得我这一直测不出来 😂

**Comment by fffonion** [comment]
晚上我重新打一个包

**Comment by piedfallow** [comment]
感谢大佬的贡献！也感谢大大的付出！

**Comment by fffonion** [comment]
改好了，顺便升级了.net框架
https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E5%9B%9B%E7%82%B9%E4%B8%80
感谢 @laisyaoran !

**Comment by piedfallow** [comment]
感谢两位大大！已经可以顺利使用了！

**Comment by piedfallow** [comment]
大大，目前又开始无法登陆了，明明验证码正确，却说我输入错误，等我关闭程式后没多久会出现下面这图，前几天已经有点问题了，今天是到现在我还无法登入，不管是使用手机版还是网页版，4.8还是3.5的都会有一样的问题
![1](https://user-images.githubusercontent.com/88279588/192572348-ba8021e1-5d01-4a67-bf35-7df6d2bde9dc.png)

**Comment by blackacrow** [comment]
我也登不上，一直提示让我用邮箱登录，但是手机号邮箱都试了都不行，密码也是没错的，net35和另一个普通的都试了。怎会如此[http://tva1.sinaimg.cn/large/dfbb3289ly1h77aqecq4cj20dj05ljsz.jpg](url)[http://tva1.sinaimg.cn/large/dfbb3289ly1h77aqo75lhj20di05l406.jpg](url)

**Comment by blackacrow** [comment]
免费的也下不了http://tva1.sinaimg.cn/large/dfbb3289ly1h77hfs8hfrj20df0jfdkt.jpg

**Comment by fffonion** [comment]
可能登录寄了，等我有空看看 🤔

**Comment by piedfallow** [comment]
謝謝大大！

**Comment by SindyQian** [comment]
大大，我也登录不上了，和@piedfallow一样的情况。我们需要你😭😭😭
![846a4f4ac1877da3253cd5d1d0d4f08](https://user-images.githubusercontent.com/118985135/203904869-013d9289-5d60-4213-9abe-10d84bfc0c3d.png)

**Comment by piedfallow** [comment]
大大最近有空修复这个软件吗?😭😭😭

**Comment by fffonion** [comment]
得找个时间把登录搞成代理或者webview的，目前先用cookie吧，已经更新了https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E5%9B%9B%E7%82%B9%E4%BA%8C

**Comment by zixue-purplesnow** [comment]
你好， 用cookie登入后会闪退 （自动关闭），请问这个能解决吗？ 已经在用最新版本了。 谢谢

**Comment by 945945** [comment]
和樓上那位一樣，用cookie登入后会闪退 （自动关闭），軟體是最新版本了，請問能修復嗎 >< 谢谢

**Comment by fffonion** [comment]
因为这个串太长了，防止话题跑偏，我先把这个关了。cookie的问题移步#22 讨论： ）
