### ISSUE TITLE
突然无法下载

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#15]
出现解码错误，不确定是哪方面问题，附上图片，试过使用以问号取代无法解码的字，但仍无法正常下载，主要是VIP章节都是如此，不同本也一样
![1](https://user-images.githubusercontent.com/88279588/174492823-7966d735-8bad-4bc3-a690-8d8e3f943695.png)
![2](https://user-images.githubusercontent.com/88279588/174492824-4c3867e0-0acd-43cd-a72f-c4842cf26c83.png)

**Comment by piedfallow** [comment]
我有试过别的下载，目前情况是都会缺字，似乎都是无法正确被解码(反爬脚本失效？)

**Comment by piedfallow** [comment]
目前已知是小说下载器作者的在线反爬字体伺服器失效，不确定您的下载器是否使用同一反爬字体脚本，如果是的话，那就等该伺服器修复就好了，抱歉打扰了

**Comment by piedfallow** [comment]
目前小说下载器的在线反爬脚本已经修复可以使用，但jjget仍旧出现错误讯息（同上），所以应该可能是晋江又改了规则？

**Comment by fffonion** [comment]
应该可以了，我更新了服务器上的软件，有点问题，现在回退了

**Comment by piedfallow** [comment]
已经可以了！谢谢大大！
