### ISSUE TITLE
无法下载文章

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#17]
大大，今天使用软体的时候无法下载，说是解密请求没有回应，勾选用问号代替解密失败的选项也无法下载，附上图片
![1](https://user-images.githubusercontent.com/88279588/184500991-dd69bb09-1c73-4cb3-84e1-8a6846fa2a90.png)

**Comment by fffonion** [comment]
可以了，我这边的服务器挂了 😸

**Comment by piedfallow** [comment]
谢谢大大！
