### ISSUE TITLE
一登陆就闪退qaq

### ISSUE THREAD

**Issue by quenlowi** [fffonion/JJGet#2]
正在登陆……正在获取用户信息……然后闪退ing
笔名和手机号登陆都是这样
大佬帮帮忙，是1.2.2最新版

**Comment by fffonion** [comment]
好的我看看

**Comment by fffonion** [comment]
我好像没问题诶，试试换个文件夹运行exe？
可能是保存的用户信息有问题

**Comment by quenlowi** [comment]
换文件夹也不行
如果验证码错误或者账号密码不对都会正常弹出提示
应该能顺利登陆的瞬间就闪退

**Comment by quenlowi** [comment]
我又试了一下，手机号登陆小号，是可以成功登陆的，但是用笔名/手机号登陆大号都不行
我只要注册了作者号（有笔名）的账号，用笔名/手机号登陆都会闪退
没有注册作者号的账号可以用手机号登陆

**Comment by quenlowi** [comment]
注册作者号用邮箱登陆也会闪退

**Comment by quenlowi** [comment]
确认了是注册作者的问题，某个小号在注册作者前可以用手机号登陆，注册作者之后再输手机号登陆就闪退，用笔名登陆也是闪退

**Comment by fffonion** [comment]
好的我来试试

**Comment by fffonion** [comment]
修好了w

**Comment by quenlowi** [comment]
成功了现在确实可以登陆作者号了！！！感谢太太！！！！另外还有一个奇怪的小bug，某id3977303的书每次下到一二章进度0%的时候就开始闪退，就是阅读未来续那篇，试了一下其他几篇文都正常没有这种问题

**Comment by fffonion** [comment]
修好啦w

**Comment by quenlowi** [comment]
谢谢太太！另外还有两件事，一是对于文案正在审核的文【文案信息正在复审或等待作者修改文案中，读者亲们请稍安勿躁~~】随便举例比如id121912这种情况下会显示错误无法读取，这个有没有办法啊qaq
二是一个小意见，能否将程序读取出来的文案（首页？）文本加入txt的最前面呢？放在第一章之前？

**Comment by fffonion** [comment]
1.2.5可以啦

**Comment by quenlowi** [comment]
谢谢太太55555555555
