### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#21]
已经使用更新版的1.4.2.0，但是无法下载，软体显示如附件
![1](https://user-images.githubusercontent.com/88279588/214472302-ca841b2d-2d51-4ca2-8a72-ce05bcfc4198.png)
![2](https://user-images.githubusercontent.com/88279588/214472305-c96b9bf3-54c6-4c8f-9a17-bd3e56794176.png)

**Comment by fffonion** [comment]
我的服务器挂了，现在应该可以了，再试试？

**Comment by piedfallow** [comment]
已經可以了！謝謝大大！新年快樂！
