### ISSUE TITLE
cookie输入确认后会闪退

### ISSUE THREAD

**Issue by motiam** [fffonion/JJGet#22]
1.4.2
输入cookie确认之后，软件显示正在登录，然后会闪退

**Comment by zixue-purplesnow** [comment]
我也有这个问题， 用cookie登入后会闪退 （自动关闭），请问这个能解决吗？ 已经在用最新版本了。 谢谢

**Comment by 945945** [comment]
同樣問題~~

**Comment by piedfallow** [comment]
![1](https://user-images.githubusercontent.com/88279588/236676953-a3eab584-6037-484c-9a40-af6c90a32a97.jpg)
我自己的解决方式，给大家参考一下

已登录 ID: 客户号 名称 信箱

**Comment by fffonion** [comment]
我看看为什么 :think:
可以先按照 @piedfallow 说的那样手动设置一下cookie : )

**Comment by 945945** [comment]
> ![3](https://user-images.githubusercontent.com/88279588/236677963-9dc01c39-f1e7-494a-a2c7-caeabd240de8.png)
> 
> 我自己的解决方式，给大家参考一下，空格要保留，cookie是大大程序所复制的那个
> 
> 已登录 ID: 客户号 名称 信箱
> 
> 贴在记事本里面后副檔名为.jjsave(只有副檔名)，和程序放一起即可 ![1](https://user-images.githubusercontent.com/88279588/236677984-eb94dfca-a50b-4710-9f8e-9a2338bf51f9.png)

暫時可以work了
非常感謝 🥹

**Comment by fffonion** [comment]
v1.4.3已修复 https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E5%9B%9B%E7%82%B9%E4%B8%89
