### ISSUE TITLE
无法解析字体

### ISSUE THREAD

**Issue by blackacrow** [fffonion/JJGet#23]
![图片](https://user-images.githubusercontent.com/43438263/230019827-b30a8357-41c2-4399-a10e-3cbbb367fd64.png)
![图片](https://user-images.githubusercontent.com/43438263/230024411-ffd617a8-313c-4921-b4a1-1f0bb8381699.png)

**Comment by piedfallow** [comment]
> ![图片](https://user-images.githubusercontent.com/43438263/230019827-b30a8357-41c2-4399-a10e-3cbbb367fd64.png) ![图片](https://user-images.githubusercontent.com/43438263/230024411-ffd617a8-313c-4921-b4a1-1f0bb8381699.png)

我自己经验是隔天再下载就可以了

**Comment by fffonion** [comment]
你好，这个应该是网络问题，我这两天更新一下服务器的线路看看
