### ISSUE TITLE
下载后显示原始码

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#25]
如题，部份文章下载后部份文字会显示原始码，但不是所有文章都是这样，上周开始出现这个问题，不过同样一篇文前后两章下载时一章为正常显示，一章部份显示原始码
![圖片](https://github.com/fffonion/JJGet/assets/88279588/0f0a09fe-9c2a-4ef2-9fbf-73cee139c0fb)
![圖片](https://github.com/fffonion/JJGet/assets/88279588/7ae92c13-742d-49c0-88dd-5495b794b55d)
图为范例，有些文章前两天下载都是正常，然后这两天下载会突然出现原始码，但是有些原本会显示原始码的，会突然正常显示

**Comment by fffonion** [comment]
应该是有一部分改成用css来加载自定义字体了，等我空了去改一下

**Comment by piedfallow** [comment]
谢谢大大！

**Comment by piedfallow** [comment]
大大如果改了可以跟我說一下嗎?謝謝😊

**Comment by fffonion** [comment]
还没去看，可能大概下周 🤔 太热了完全不想动aaaaaaaaaa

**Comment by 945945** [comment]
我的下载后前面也都會显示原始码了 t_t" 求救援

**Comment by piedfallow** [comment]
大大，有想动的想法了吗？😂我们需要您的救援QAQ

**Comment by fffonion** [comment]
v1.4.3已修复 https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E5%9B%9B%E7%82%B9%E4%B8%89

**Comment by piedfallow** [comment]
已經可以了！謝謝大大！

**Comment by fffonion** [comment]
好耶！

**Comment by 945945** [comment]
謝謝大大救援!!!!
