### ISSUE TITLE
怎么用不了了啊TT

### ISSUE THREAD

**Issue by twistedme2** [fffonion/JJGet#26]
前几天是不能下载，今天解析首页都不行了。
![无标题](https://github.com/fffonion/JJGet/assets/134989840/547f22e4-2715-4d29-b1ea-371d01e2331e)

**Comment by twistedme2** [comment]
重新下了一遍能分析首页了
但是下载还是不行TT
![图片](https://github.com/fffonion/JJGet/assets/134989840/9d9215a6-fc5f-4906-bf40-471d95bfcc6d)

**Comment by piedfallow** [comment]
非V章節我都是直接手動下載，因為我的好像一直都不行

**Comment by fffonion** [comment]
v1.4.3已修复 https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E5%9B%9B%E7%82%B9%E4%B8%89
