### ISSUE TITLE
不确定是啥问题

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#27]
大大，刚刚试用了最新的版本，目前最新章下载已经不会显示原始码了，但是如果整本下载会在某些章节显示无法下载，附上截图，试过两本不一样的文，不确定问题是什麽，虽然截图用的是同一篇文，然后我试过勾选用问号代替无法解码的地方，仍无法顺利下载，都是V章，非V章已经可以正常下载
![1](https://github.com/fffonion/JJGet/assets/88279588/eb416630-fbbf-40b2-af18-417912be8872)
![2](https://github.com/fffonion/JJGet/assets/88279588/e37a6231-cf28-4668-83e4-416f939d854d)

**Comment by fffonion** [comment]
是我的问题 
![IMG_5678](https://github.com/fffonion/JJGet/assets/2135445/a982b06a-fcb8-44dc-b700-fc48878ffef8)

修好了 https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E5%9B%9B%E7%82%B9%E5%9B%9B

**Comment by piedfallow** [comment]
已經完全可以了，謝謝大大！
