### ISSUE TITLE
输入cookie后点"确定"后一会儿就闪退

### ISSUE THREAD

**Issue by 5jos** [fffonion/JJGet#28]
Win10系统，安装.Net 4.8提示已有更高版本。
下载旧版本的也是输入cookie点"确定"后“正在获取用户信息”卡一会儿就闪退。
您好，请问这个怎么办呀QAQ

**Comment by fffonion** [comment]
你好，系统自带.net就不用安装了
目前cookie可用的版本是1.4.4

**Comment by FuruhashiFumino** [comment]
大大求助，我也一样输入cookie后就闪退
下了前面几个版本都不行，Net 4.8电脑也是自带的，换了两台电脑两台电脑都一样闪退QAQ

**Comment by fffonion** [comment]
如果确定cookie没问题，可以用记事本打开 .jjsave 文件，然后把cookie直接贴到里面

**Comment by fffonion** [comment]
1.4.5.0修复啦
