### ISSUE TITLE
经常遇到某个字符解码错误或者不在字典中怎么解决？谢谢

### ISSUE THREAD

**Issue by TiantianGuo1231** [fffonion/JJGet#29]
勾选了使用问号代替也中断下载了

**Comment by fffonion** [comment]
用的最新版本吗？

**Comment by TiantianGuo1231** [comment]
对的，百度镜像里1.4.3

**Comment by TiantianGuo1231** [comment]
> 用的最新版本吗？

对的，百度镜像里1.4.3

**Comment by fffonion** [comment]
用这个 https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E5%9B%9B%E7%82%B9%E5%9B%9B
百度镜像忘记更新了 😢

**Comment by TiantianGuo1231** [comment]
> 用这个 https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E5%9B%9B%E7%82%B9%E5%9B%9B 百度镜像忘记更新了 😢

目前尝试的小说没有问题，谢谢大佬！
