### ISSUE TITLE
vip章节显示账号没有购买或登陆过期

### ISSUE THREAD

**Issue by quenlowi** [fffonion/JJGet#3]
退出重新登陆也不管用，确认是买了的v章

**Comment by fffonion** [comment]
好的我康康

**Comment by fffonion** [comment]
修好啦！https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E4%B8%89%E7%82%B9%E9%9B%B6

**Comment by fffonion** [comment]
如有仍有问题请重开issue :)
