### ISSUE TITLE
不确定是哪边的问题

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#30]
最近有发现可以看到该章节，但是软件节读不到该章节
![1](https://github.com/fffonion/JJGet/assets/88279588/6a33ce60-a360-4cd7-8c3d-6b80f372e969)
![2](https://github.com/fffonion/JJGet/assets/88279588/eaf32537-4783-431d-8e49-afd49f768644)

**Comment by fffonion** [comment]
诶，现在还有这问题吗

**Comment by piedfallow** [comment]
目前已经没有该问题了，谢谢大大
