### ISSUE TITLE
无法解析字体，然后中断下载，试了好几次都不行。

### ISSUE THREAD

**Issue by twistedme2** [fffonion/JJGet#31]
版本是1.4.4，度盘里的最新版了。
而且这章是以前下过的，今天解析就出问题了，勾选了用？替代也不行。
如果下载的时候能选择追加而不是每次都从头下就好了
![image](https://github.com/fffonion/JJGet/assets/134989840/6fe76055-c309-41b8-848c-d586289b3472)

**Comment by fffonion** [comment]
服务端问题，可以过段时间重试一下
