### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#32]
今天下载时遇到该问题，但有些可以正常下载，有些只能下载前两章，后面无法下载
![1](https://github.com/fffonion/JJGet/assets/88279588/33bafe06-1e83-4e22-ad57-f546d05eca48)

**Comment by twistedme2** [comment]
同样的问题，希望作者看过来🙏

**Comment by fffonion** [comment]
有空我看一下 🤔

**Comment by fffonion** [comment]
有点蛋疼，我看了一下日志都是比较后面的V章，等我搞一个能生成调试信息的版本出来

**Comment by piedfallow** [comment]
谢谢大大，不确定是不是晋江又改防盗，因为下载目前看起来从V章开始，每隔一章就可以正常下载，有看到别的下载软体的解决
的解决方式是说需要手动输入登录 token
![1](https://github.com/fffonion/JJGet/assets/88279588/f65c7750-f549-4df5-9f2d-20bd93e69043)

**Comment by fffonion** [comment]
修好了捏

**Comment by fffonion** [comment]
就很离谱，相邻的两个章节会用不同的加密方式（

**Comment by piedfallow** [comment]
大大，还是不行，它说遇到错误，我试了两篇不同的文章也不行
![1](https://github.com/fffonion/JJGet/assets/88279588/514e2490-2d0c-4d72-8934-90b45b389d49)
![2](https://github.com/fffonion/JJGet/assets/88279588/d57a9f20-359b-42eb-8e99-850e69e76cb1)

**Comment by fffonion** [comment]
再试试，我写了个一个bug 😄

**Comment by piedfallow** [comment]
大大，还是不行，一样显示上面的内容，资料错误

**Comment by fffonion** [comment]
又修了一下！

**Comment by fffonion** [comment]
生成调试信息和输入cookie闪退的版本也发布惹

**Comment by piedfallow** [comment]
已经可以了！谢谢大大！大大辛苦了！
