### ISSUE TITLE
输入cookie后闪退

### ISSUE THREAD

**Issue by yuxx817133** [fffonion/JJGet#33]
版本1.4.4。win10系统，自带.net
输入cookie后就闪退了，不管输什么都闪退，求助

**Comment by fffonion** [comment]
如果确定cookie没问题，可以用记事本打开 `.jjsave` 文件，然后把cookie直接贴到里面

**Comment by fffonion** [comment]
可以直接用记事本新建一个文件保存为.jjsave

**Comment by onediary** [comment]
> 可以直接用记事本新建一个文件保存为.jjsave

好的。谢谢。不过又出现问题了。
![屏幕截图 2023-10-30 215308](https://github.com/fffonion/JJGet/assets/33566264/037c9301-48a0-4b8d-bb0a-b77f09a9845c)
显示这个

**Comment by fffonion** [comment]
那现在和#32 一样了，我先把这个关掉了，有更新在那个issue里发布
