### ISSUE TITLE
杀毒软件误报

### ISSUE THREAD

**Issue by lyc8503** [fffonion/JJGet#34]
Release 的文件下载下来就被杀软干掉了... 去扫了一下, 似乎有一些厂家的误报, 不知道是使用了什么导致报毒.

VirusTotal 6/72
https://www.virustotal.com/gui/file/7df0d498b99fb118b1261215ced0b46ea2e5ba254cf57ebdecbbd96581c747ed/detection

不过下载功能很好用, 感谢作者~

**Comment by fffonion** [comment]
用了ILRepack来把依赖dll合并到了一个exe。应该是运行时会自解压，所以会被淦

**Comment by lyc8503** [comment]
了解了, 其实不合并也行的, 反正都是压缩包下载, 报毒反而给我带来了一些麻烦😂
