### ISSUE TITLE
文章抓取问题

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#35]
大大，最近发现一个问题，就是页面显示有287章，但使用程式只抓取到285章，目前看到好几篇都有这个问题，不确定是哪边出问题了，但抓到的文章可以正常下载
更新一下：发现是VPN的问题，使用香港的VPN可以显示最新文章，但因为程式是使用本地下载，所以无法显示最新

**Comment by fffonion** [comment]
可能是jj的cdn问题，可以在软件里设置代理下载
