### ISSUE TITLE
无法下载V章

### ISSUE THREAD

**Issue by lizliveitup** [fffonion/JJGet#37]
大大您好！我用#33中提出的解决办法创建了.jjsave文件，创建后输入文章ID无法get文章信息，删除.jjsave后软件显示已登录可以下载，但无法下载V章。求解决~~谢谢！

![image](https://github.com/fffonion/JJGet/assets/33726874/fd45d1fb-792f-4371-b57f-18d03122e6f7)
图1 添加.jjsave无法get文章信息

![image](https://github.com/fffonion/JJGet/assets/33726874/6ce1bb18-5e16-4fd2-8e6d-711bf239be34)
图2 删除.jjsave后无法下载V章

**Comment by lizliveitup** [comment]
p.s 无jjsave文件用ID get到首页信息后，再把jjsave加回来也下载不了v章……

**Comment by fffonion** [comment]
@lizliveitup 创建 .jjsave 文件的时候要删除末尾的换行

**Comment by lizliveitup** [comment]
把两个换行符删掉后能正常使用了！感谢！

**Comment by fffonion** [comment]
那我关了！
