### ISSUE TITLE
出现下载错误

### ISSUE THREAD

**Issue by piedfallow** [fffonion/JJGet#41]
今天下载的时候出现该错误，每一篇都是如此，附上bug日志与截图
![1](https://github.com/user-attachments/assets/7da48b1b-b837-44a0-9536-f6505811e9ea)
[jjdebug.zip](https://github.com/user-attachments/files/17356008/jjdebug.zip)

**Comment by onediary** [comment]
这个问题我也遇到了。只能等作者看到或者有空闲的时候修复吧

**Comment by fffonion** [comment]
修好了，再试试吧 ：）
VIP章节那个问题我还没来得及看

**Comment by onediary** [comment]
> 修好了，再试试吧 ：） VIP章节那个问题我还没来得及看

刚刚登录试了一下。
![Uploading 屏幕截图 2024-10-20 214717.png…]()

**Comment by onediary** [comment]
![屏幕截图 2024-10-20 214717](https://github.com/user-attachments/assets/7b7673ff-2fb9-4551-8d18-13fc5c259fdd)

**Comment by fffonion** [comment]
ok了：）
