### ISSUE TITLE
在章节22处遇到错误 字体jjwxcfont_0023v中的字符eb4a无法解码

### ISSUE THREAD

**Issue by xxxx96923** [fffonion/JJGet#6]
下载第22章的时候遇到的该错误

**Comment by fffonion** [comment]
改进了一下算法，再试一下？:smile:

**Comment by xxxx96923** [comment]
这个好了，但是又出现了字体 jjwxcfont_004hu 中的字符 e401 无法解码

**Comment by fffonion** [comment]
我又改了一下，目前看来没问题，但是可能还是会有误识别

如果加一个选项，允许解码失败时直接用问号替代，你觉得怎么样? 🤔

**Comment by xxxx96923** [comment]
这得看一篇文里解码失败的字符多不多，如果不多的话，影响不大

**Comment by fffonion** [comment]
从统计来看最多是一个字符的失败，而且因为是常用字，应该也可以通过上下文猜出来。那我去加个开关

**Comment by fffonion** [comment]
更新了1.3.1 https://github.com/fffonion/JJGet/releases/tag/v%E4%B8%80%E7%82%B9%E4%B8%89%E7%82%B9%E4%B8%80

**Comment by fffonion** [comment]
应该没问题了，这个我先关了，有问题可以重开一个issue ： ）
